{
  "entity": {
    "location": {
      "namespaceTitle": "Uno.Threading",
      "namespaceUri": "uno/threading",
      "packageName": "Uno.Threading",
      "packageVersion": "1.8.0-rc1"
    },
    "parameters": [
      {
        "name": "reason",
        "href": "uno/exception",
        "title": "Exception",
        "fullyQualifiedTitle": "Uno.Exception"
      }
    ],
    "id": {
      "id": "uno/threading/future_1/internalreject_533b340b",
      "parentId": "uno/threading/future_1",
      "type": "Method",
      "modifiers": [
        "protected"
      ]
    },
    "uri": {
      "idUri": "uno/threading/future_1/internalreject_533b340b",
      "href": "uno/threading/future_1/internalreject_533b340b"
    },
    "titles": {
      "pageTitle": "Future.InternalReject Method (Exception)",
      "navigationTitle": "InternalReject Method (Exception)",
      "fullTitle": "Uno.Threading.Future`1.InternalReject",
      "indexTitle": "InternalReject(Exception)",
      "fullyQualifiedIndexTitle": "Uno.Threading.Future.InternalReject(Uno.Exception)"
    },
    "syntax": {
      "uno": "protected voidInternalReject(Uno.Exception reason) {}"
    }
  },
  "tableOfContents": {}
}